//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ControleDeTarefas {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ResourceStringTable {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ResourceStringTable() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ControleDeTarefas.ResourceStringTable", typeof(ResourceStringTable).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Abrir.
        /// </summary>
        internal static string BtnAbrir {
            get {
                return ResourceManager.GetString("BtnAbrir", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gerar.
        /// </summary>
        internal static string BtnGerar {
            get {
                return ResourceManager.GetString("BtnGerar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Controle De Tarefas.
        /// </summary>
        internal static string FormNome {
            get {
                return ResourceManager.GetString("FormNome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nome Janela.
        /// </summary>
        internal static string JanelasLabelNomeJanela {
            get {
                return ResourceManager.GetString("JanelasLabelNomeJanela", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nome Proc.
        /// </summary>
        internal static string JanelasLabelNomeProc {
            get {
                return ResourceManager.GetString("JanelasLabelNomeProc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Proc ID.
        /// </summary>
        internal static string JanelasLabelProcID {
            get {
                return ResourceManager.GetString("JanelasLabelProcID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Janelas.
        /// </summary>
        internal static string TabNomeJanelas {
            get {
                return ResourceManager.GetString("TabNomeJanelas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Relatório.
        /// </summary>
        internal static string TabNomeRelatorio {
            get {
                return ResourceManager.GetString("TabNomeRelatorio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tarefas.
        /// </summary>
        internal static string TabNomeTarefas {
            get {
                return ResourceManager.GetString("TabNomeTarefas", resourceCulture);
            }
        }
    }
}
